# Generated by Django 5.0.1 on 2024-01-20 13:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apostilas', '0002_viewapostila'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apostilas',
            new_name='Apostila',
        ),
    ]
